{"time":"2025-02-12T22:54:20.0613115+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.4","symlink path":"C:\\Users\\proik\\demo\\wandb\\run-20250212_225419-b412rxj3\\logs\\debug-core.log"}
{"time":"2025-02-12T22:54:20.3195345+01:00","level":"INFO","msg":"created new stream","id":"b412rxj3"}
{"time":"2025-02-12T22:54:20.3200612+01:00","level":"INFO","msg":"stream: started","id":"b412rxj3"}
{"time":"2025-02-12T22:54:20.3200612+01:00","level":"INFO","msg":"handler: started","stream_id":"b412rxj3"}
{"time":"2025-02-12T22:54:20.3205827+01:00","level":"INFO","msg":"sender: started","stream_id":"b412rxj3"}
{"time":"2025-02-12T22:54:20.3205827+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"b412rxj3"}
{"time":"2025-02-12T22:54:20.6504042+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-12T23:18:43.6260641+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.178.52:60819->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-12T23:31:11.9852159+01:00","level":"INFO","msg":"stream: closing","id":"b412rxj3"}
{"time":"2025-02-12T23:31:11.9852159+01:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-02-12T23:31:11.990883+01:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-02-12T23:31:12.8310012+01:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-02-12T23:31:13.0786148+01:00","level":"INFO","msg":"handler: closed","stream_id":"b412rxj3"}
{"time":"2025-02-12T23:31:13.0786148+01:00","level":"INFO","msg":"writer: Close: closed","stream_id":"b412rxj3"}
{"time":"2025-02-12T23:31:13.079292+01:00","level":"INFO","msg":"sender: closed","stream_id":"b412rxj3"}
{"time":"2025-02-12T23:31:13.079292+01:00","level":"INFO","msg":"stream: closed","id":"b412rxj3"}
