{"time":"2025-02-22T01:22:38.4337757+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.4","symlink path":"C:\\Users\\proik\\Desktop\\Demo\\wandb\\run-20250222_012238-78yrc8yy\\logs\\debug-core.log"}
{"time":"2025-02-22T01:22:38.5469287+01:00","level":"INFO","msg":"created new stream","id":"78yrc8yy"}
{"time":"2025-02-22T01:22:38.5474983+01:00","level":"INFO","msg":"stream: started","id":"78yrc8yy"}
{"time":"2025-02-22T01:22:38.5474983+01:00","level":"INFO","msg":"handler: started","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:22:38.5474983+01:00","level":"INFO","msg":"sender: started","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:22:38.5474983+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:22:38.867232+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-22T01:43:46.6308448+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.178.52:49485->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-22T01:54:40.4119715+01:00","level":"INFO","msg":"stream: closing","id":"78yrc8yy"}
{"time":"2025-02-22T01:54:40.4124743+01:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-02-22T01:54:40.4136456+01:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-02-22T01:54:41.2090867+01:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-02-22T01:54:41.4405388+01:00","level":"INFO","msg":"handler: closed","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:54:41.4405388+01:00","level":"INFO","msg":"writer: Close: closed","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:54:41.4405388+01:00","level":"INFO","msg":"sender: closed","stream_id":"78yrc8yy"}
{"time":"2025-02-22T01:54:41.4417523+01:00","level":"INFO","msg":"stream: closed","id":"78yrc8yy"}
